### ISSUE TITLE
Refactor Project Structure

### ISSUE THREAD

**Issue by ojaswa1942** [parulsurana/Classroom#1]
As the project size increases with time, it is necessary to keep a structure in mind at the time of beginning. For this project, I suggest the following:

- src
-- assets (this will contain all images, other assets)
-- components (this will contain all minimal components)
-- views/pages (this will contain each folder for each kind of view)
-- utilities (helper functions, custom hooks, etc if required)
-- App.js (This will only contain routes to each page and root states which are required throughout the application)

**Comment by sejal8745** [comment]
Hanji sir, now we have changed the old format.
